# Generated by Django 5.2.1 on 2025-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email'),
        ),
    ]
