# Generated by Django 5.2.1 on 2025-07-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_register_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('photo', models.ImageField(upload_to='teachers_photos/', verbose_name='Photo')),
                ('specialization', models.CharField(default='General Yoga', max_length=100, verbose_name='Yoga Specialization')),
            ],
        ),
    ]
