# Generated by Django 5.2.1 on 2025-08-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
